-- studentresfinder SQL scaffold
CREATE TABLE USERS (
    USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100),
    ROLE VARCHAR(20)
);
CREATE TABLE LISTINGS (
    LISTING_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR(150),
    DESCRIPTION VARCHAR(255),
    PRICE DOUBLE,
    LOCATION VARCHAR(100),
    IMAGE_PATH VARCHAR(255),
    LANDLORD_ID INT,
    FOREIGN KEY (LANDLORD_ID) REFERENCES USERS(USER_ID)
);
CREATE TABLE VERIFICATION (
    VERIFICATION_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LANDLORD_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Pending',
    FOREIGN KEY (LANDLORD_ID) REFERENCES USERS(USER_ID)
);